Move NCCL LD_PRELOAD to nvidia_nccl role
Having the setting on aws_efa role causes
ERROR: ld.so: object '/opt/nccl/build/lib/libnccl.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
in Trn1 AMI